### ISSUE TITLE
BrokerService.UnregisterSubscriberAsync deletes the subscriber actor message queue

### ISSUE THREAD

**Issue by schernets** [loekd/ServiceFabric.PubSubActors#1]
When my actor after handling a specific TMessage unsubscribes from it, the subject method removes the corresponding subscriber from `_queues` ConcurrentDictionary as well as the message queue. Hence, subsequent messages are not delivered.

```
await StateManager.RemoveAsync(tx, reference.GetQueueName());
await StateManager.RemoveAsync(tx, reference.GetDeadLetterQueueName());
ServiceEventSourceMessage($"Unregistered subscriber: {reference.Name}");
_queues.TryRemove(reference.GetQueueName(), out reference);
```

**Comment by loekd** [comment]
Thank you for taking the time to investigate this. I've published a new version (4.5..4) which should resolve this issue. Please have a look and let me know.

**Comment by Sterlingg** [comment]
@loekd I see the 4.5.4 package of "ServiceFabric.PubSubActors", but I can't update my NuGet package yet because the "ServiceFabric.PubSubActors.Interfaces" NuGet package isn't yet update to version 4.5.4. Thanks for the quick fix on this.

**Comment by schernets** [comment]
@loekd Thanks a lot for the fix. Will be testing this the next sprint. However, as @Sterlingg mentioned we do need NuGet to be fixed first.

**Comment by loekd** [comment]
Sorry, there was an error in the build pipeline. It's published now.
