### ISSUE TITLE
Consider other licensing for interface packages

### ISSUE THREAD

**Issue by NickDarvey** [loekd/ServiceFabric.PubSubActors#10]
Hello, you guys are doing some awesome things for SF!
We'd love to start using this in our projects but we'd need (as far as I can tell) the NuGet packages available as something more permissive (like LGPL or MIT) so that we don't need to open-source our client's business logic by adding the interface packages to our projects. Is that something you'd consider?
Either way, keep up the great work,
Nick

**Comment by loekd** [comment]
done!

**Comment by NickDarvey** [comment]
Thank you so so so much!
