### ISSUE TITLE
Getting exception when following the "Getting started"

### ISSUE THREAD

**Issue by fiatkongen** [loekd/ServiceFabric.PubSubActors#102]
Hi

What at great project, just what I am looking for. I have followed the simplest instructions, but this Exception is logged when running: 

`RunAsync - Exception caught while processing messages:'NamedEndpoint 'SubscriberStatelessServiceRemotingListener' not found in the address '{"Endpoints":{"":"http:\/\/XXX:32093"}}' for partition '8501a14e-3585-4fc7-a627-3918dc5d1ee7''`

Hope you can help :-)

**Comment by danadesrosiers** [comment]
It sounds like you may not have registered the service.  See the example in the source code: 
https://github.com/SoCreate/service-fabric-pub-sub/blob/master/examples/SoCreate.ServiceFabric.PubSubDemo.SampleStatelessSubscriber/Program.cs 

Also make sure the ServiceManifest is set up correctly.  Make sure you are using V2 listeners.
https://github.com/SoCreate/service-fabric-pub-sub/blob/master/examples/SoCreate.ServiceFabric.PubSubDemo.SampleStatelessSubscriber/PackageRoot/ServiceManifest.xml 

If that doesn't help, I would need to see some code.  In general, I would look to the example app for hints.

**Comment by fiatkongen** [comment]
Thank you for the pointers :-)
My problem was that I had inherited from the `SubscriberStatelessServiceBase `but also had overriden the `IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()`. All worked out once I stopped inhering from the Base class, following the instructions from the section **Using Services Without the Base Class**

Looking forward to using this awesome project
