### ISSUE TITLE
net6

### ISSUE THREAD

**Issue by tazdevilnl** [loekd/ServiceFabric.PubSubActors#108]
Are there plans to upgrade to net6?

**Comment by danadesrosiers** [comment]
Good question!  An upgrade is certainly needed.  We are too busy over here to spend time on it right now, but PR's are welcome.

**Comment by isakengstrom** [comment]
The project files are updated to .Net 6. Shouldn't this issue be closed?

**Comment by danadesrosiers** [comment]
Yes, thanks.  Fixed by #108
