### ISSUE TITLE
Converting the project to cspoj

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#11]
Since the xproj and project.sjon are going away for .NET core, it might make sense to convert the project to csproj. What you think?

**Comment by loekd** [comment]
I totally agree. My idea was to do that once VS2015 tools come out of preview, or when VS2017 goes RTM. Do you need it sooner?

**Comment by alltej** [comment]
Not really. The reason being I want to project reference the ServiceFabric.PubSubActors and ServiceFabric.PubSubActors.Interfaces projects from the demo project so I can step through it. But looks like nuget manager is not finding it because they are xproj. Let me know if there is another work around. Thanks

**Comment by alltej** [comment]
Ignore about referencing the libraries. I got it work.

**Comment by loekd** [comment]
For any other readers that want to debug, you don't need a project reference.

Symbols are published here: http://www.symbolsource.org/Public/Home/VisualStudio
Manually open the file you want to debug, and put a breakpoint.

Option two would be to install .net core on your machine, compile the project to get the PDB's and manually load symbols using the Debug->Windows ->Modules window in Visual Studio.

**Comment by alltej** [comment]
@loekd If I need to modify some code in the package(ServiceFabric.PubSubActors) itself, so I think I need to project reference the package code from the demo project, so I can step through the modified code. So not sure if I am setting up my environment correctly for this project.

**Comment by loekd** [comment]
Changing the code is a lot easier with project references indeed.

**Comment by loekd** [comment]
@alltej I've converted to VS2017 & csproj files.

**Comment by alltej** [comment]
thanks for converting it! also thanks for accepting my PR :)
