### ISSUE TITLE
What is the ServiceFabric.PubSubActors.LoadDemo sample project for?

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#12]
I am able to run the other demo project (ServiceFabric.PubSubActors.Demo) and got an understanding of it but for ServiceFabric.PubSubActors.LoadDemo, not sure what use case it is for?

**Comment by loekd** [comment]
I've added 2 demo projects. The first is to show all the library functionality. The second is to do some reliability testing. By changing the configuration of the [publisher ](https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors.LoadDemo/PublisherService/PackageRoot/Config/Settings.xml) and subscriber, you can see if it performs up to your standards. 

I use it to see if code changes don't impact performance negatively, and to see how it holds under load.

**Comment by alltej** [comment]
thanks @loekd !
