### ISSUE TITLE
Multiple stateless subscribers and one stateful service to handle retry queue

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#16]
Option1: Multiple stateless subscribers and one stateful service to handle retry queue
The stateful service will process the failed events and republish an event that subscribers will listen.

Option2: Is to make each subscriber stateful and handle their own retry of failed process.

What is the best/better option?

**Comment by loekd** [comment]
I'm sorry, but I don't understand what you mean. What problem do you need to solve?

**Comment by alltej** [comment]
Existing subscribers are stateless.  If a work item fails in the subscriber (e.g. a call to external API fails), it queue the work item to a stateful service for tracking purpose. This stateful service can run a retry process(later) and can publish/send it back to the subscriber(s). This option gives me several stateless services instances (up to # of VMs/nodes).

The other option is to make these subscribers stateful and track/retry their own queue of failed work items. This option will have the subscribers handle their own retry (no dependency to external stateful service) but instances running will be limited to one primary and two secondary (for the default config of one partition).

Just wondering if the stateful subscribers will be an overkill.

**Comment by loekd** [comment]
It depends on the availability of the external API.

- If it's 'always there' you can likely get away with a simple retry pattern in your API caller. 

- If it's less reliable, you can store the message somewhere while you try to send it out.

Option Two sounds most solid to me. Receive a message as a subscriber, store it in a ReliableQueue, process the Queue in RunAsync (much like the BrokerService does). This way it can process outgoing API calls in its own pace and deal with API outages. 

You will get a tiny delay between the ocurring of the event and it's delivery to the API, but it will be robust.

You can configure as many partitions as you need as message processors. 

Does this help?

**Comment by alltej** [comment]
Yes, thank you!
