### ISSUE TITLE
Stateful Subscriber Service with multiple partitions

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#18]
The stateful subscriber in the demo example uses a single partition. How can I publish to a stateful subscriber that uses multiple partitions?

**Comment by loekd** [comment]
Stateless service instances share one subscription. Instance count doesn't affect this. You can't target specific instances with this library.

**Comment by loekd** [comment]
Targeting specific instances requires customized communication (hosting a REST api endpoint within each service instance for instance). It can be done, but it's not easily retrofitted.

**Comment by johnkattenhorn** [comment]
I'm embarrassed to say that we didn't try this out and then realised when we pushed the code into a cluster with multiple partitions we start seeing multiple publish and subscribe events.

We've written a sort of hash function which allows us to at least ignore the events in each partition which are not relevant but we are concerned that this might be a reason for some of the performance issues we are seeing.
