### ISSUE TITLE
Using Concurrent Reliable Queues

### ISSUE THREAD

**Issue by johnkattenhorn** [loekd/ServiceFabric.PubSubActors#21]
Following the work we've done over the last few days we have decided for fork the repo and some of the features we added:

We would happily PR back work if there is another interest but some of it might be too specific or introduce unwanted dependencies.

For features which are not either of these we will PR back as we go:

Here is a version with the Concurrent Queue implementation instead of reliable queues. In our tests this was 780% faster that the reliable queue version; however these queues are in preview right now and they also don't guarantee order so if that's important for you than this is not for you.

https://github.com/Applicita/ServiceFabric.PubSubActors/tree/feature/reliable-concurrent-queues

We are planning to modify the BrokerLocator potentially to allow you to run two Broker Services of each type and direct events which make sense for those events. Please give us your feedback and we will try to be good Open Source citizens!

**Comment by loekd** [comment]
I like the thought of being able to run both queuing options at the same time.

I'd probably choose to create an abstract 'BrokerServiceBase' class with 2 implementations. One that uses the regular queue and one with the concurrent queue. This way there'd be no need to make and maintain 2 almost identical copies of the BrokerService code.

I'm also not sure if the message type should determine the way it's transmitted. It does reduce the chance of developer errors, but I prefer explicit publish and subscribe operations (at this time, in my thoughts). Using a custom helper that adds this functionality is easy, but it shouldn't be restricted in the library. 

Thanks for the feedback and the continued efforts to make the library better.

**Comment by henricj** [comment]
I'm just skimming through ConcurrentBrokerService.cs, so take my observations as such.

The _initializer is a ManualResetEventSlim().  Why not use a TaskCompletionSource?  Some further refactoring may render the _semaphore redundant.

Why does RunAsync() need more  than one "cts" instance?  ProcessQueues() should return an uncompleted Task almost immediately so the individual ProcessQueues() should all start at about the same time (even if not, it could easily be wrapped in a Task.Run())?

The loop over the subscribers in PublishMessageAsync() is done sequentially.  Couldn't they be done in parallel?  (Something like, "await Task.WhenAll(subscribers.Select(async subscriber => { loop body here });")

**Comment by loekd** [comment]
Hi, thanks for your feedback! 
- I like the ManualResetEventSlim. The end result is the same. The semaphore enforces single access to the init operation. It's only accessed once.
- I think you're correct about this. I'll change it.
- You can't use multiple threads within an ASF transaction. Also I don't want to keep track of which consumer has which message enqueued successfully. So all consumers get the message enqueued in one big transaction, with retry wrapped around it.

**Comment by henricj** [comment]
I suppose I'm reacting to the juxtaposition of blocking and non-blocking synchronization between the semaphore, event, and the await-based coroutines involved here.  It sure looks like it does the right thing, but one can do it with only coroutine-based synchronization (well, barring a CAS in this case):  https://pastebin.com/yyqcacF6

Looking at the PublishMessageAsync() again I see that it is enqueuing the message, not actually sending it off to the subscriber.  Yeah, that should absolutely be in one shared transaction...

At the risk of stepping into something that sometimes gets political, why so few .ConfigureAwait(false) calls?

**Comment by loekd** [comment]
I don't like the added complexity (opinion). 
Adding ConfigureAwait's everywhere would be a nice optimization.

**Comment by loekd** [comment]
Have a look at https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors/BrokerServiceUnordered.cs

The load test demo project is able to use both implementation, make sure you don't auto-register both. Use `enableAutoDiscovery` false in ctor, and pass the service name when publishing using `PublishMessageAsync`.

**Comment by henricj** [comment]
> I don't like the added complexity (opinion).

Come to think of it, it's pretty much just AsyncLazy (there are a few implementations out there).
