### ISSUE TITLE
Data Contract Serialization

### ISSUE THREAD

**Issue by ben-kotvis** [loekd/ServiceFabric.PubSubActors#22]
I was trying to use this in place of an existing service where I have a class structure like this:

`
class ClassA : BaseClassA
{
     public BaseClassB ClassB { get; set; }
}

class ClassB : BaseClassB
{
     public string NotDeserialized { get; set; }
}
`

The service fabric ActorProxy or ServiceProxy would have allowed me to cast the ClassB property in the ClassA instance and get the NotDeserialized property.  With this pub sub model it is using Newtonsoft's JSON serialization.  Which means the ClassB property in ClassA is only getting the BaseClassB properties after deserialization.  I am considering making an option on the BrokerService to use JSON serialization or Data Contract serialization.  There would have to be an additional wrapper for the message wrapper and publishers.  I guess I am wondering if there is any reason you chose to use the JSON serializer.  If not I may create a pull request.

**Comment by loekd** [comment]
I'm using the Json serializer because it's one of the most popular serializers available today. I've looked into adding DI for this, and it's doable. Is this a showstopper for you?
