### ISSUE TITLE
Obsolete instruction in getting started.

### ISSUE THREAD

**Issue by Iain-Stevenson** [loekd/ServiceFabric.PubSubActors#23]
Getting started suggests using a now obsolete mechanism;
It would be more helpful to newcomers to illustrate the new way of doing things.

> 3.2. From a Service:
> 
> using ServiceFabric.PubSubActors.PublisherServices;
> [..]
> this.PublishMessageToBrokerServiceAsync(..);	//use any JSON serializable object as a message
> 

```
[Obsolete("Use ServiceFabric.PubSubActors.Helpers.PublisherServiceHelper for testability")]
public static Task PublishMessageToBrokerServiceAsync(this StatelessService service, object message, Uri brokerServiceName = null);
       
```

**Comment by loekd** [comment]
Thanks for your feedback.
You're right, I've changed the readme.

**Comment by Iain-Stevenson** [comment]
I really like this stuff btw. 

Thanks for sharing it. 

This pattern and code allows me to re-engineer my API pipeline to be more responsive to clients.
