### ISSUE TITLE
Broker Actor and Broker Service in the SF App

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#26]
Can you use/have a Broker Actor and a Broker Service when using this SF pub/sub app framework? My current solution already using the Broker Service model but just wondering if I can add another broker that is of type Broker Actor. Will it have side effects?

**Comment by loekd** [comment]
Yes that'll work. It's currently working that way in the demo app.
Please note that the `BrokerActor ` isn't battle tested (- at least - by me). 
Its state isn't immutable, so it may produce unexpected results when Actors crash.
