### ISSUE TITLE
BrokerActor state is mutable

### ISSUE THREAD

**Issue by loekd** [loekd/ServiceFabric.PubSubActors#28]
BrokerActor should have immutable state.

The class:
https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors/State/BrokerActorState.cs

Should be more like:

https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors/State/BrokerServiceState.cs

**Comment by danadesrosiers** [comment]
Closing this ticket since BrokerActor has been removed as of v8.0.
