### ISSUE TITLE
Single subscriber processing many messages of the same type in parallel?

### ISSUE THREAD

**Issue by MonDeveloper** [loekd/ServiceFabric.PubSubActors#31]
For the use case:
- Only one single Message Type
- StatelessService (or Statefull) as Subscriber
- Unordered Execution allowed (_it's ok using the new BrokerServiceUnordered_)
- Long "ReceiveMessage" execution time (_> 30 sec_)
- parallel execution of "ReceiveMessage" at subrscriber side is allowed
Is it feasible to you to allow the Broker to push messages in parallel? What are the side effects?
(_as far as I understood the Concurrent Reliable Queue allow multiple transactions in parallel_)

If the above case does have a sense:
Could we consider not only the StatelessService (or Statefull) but also an Actor? (_for sure the actor will re-introduce a serialization in the elaboration processing but this should be transparent to the broker, isn't it?_)

In case it does not have any sense, how to treat the long-processing messages?
Maybe creating some queue at subscriber side to store the messages before starting the real execution?

Thank in advance for any suggestion!

**Comment by loekd** [comment]
Message delivery happens inside a transaction to ensure guaranteed at-least-once-delivery. Those transactions shouldn't take too much time, or other subscribers will be starved. Would it work if your subscribing service / actor would receive the message and enqueue it locally, and then asynchronously process their local queue?  (using code that is very similar to the broker)

**Comment by MonDeveloper** [comment]
This is exactly what I've implemented.
But I'm still wondering if this "subscriber queue" could or could not (should or should not) be considered as a part of the "PubSub" infrastructure (read: your PubSub Library).
I mean, in the same way (a brilliant idea) you introduced 2 flavor of brokers (standard and unordered) because there are different needs at "publishing side" we could think at my problem in the same way and provide a sort of SubscriberServiceBaseClass for any "long running" subscribers.
This will cover a real case need without asking the adopters to create it from scratch everytime.

(I didn't spend more than 1ms to think at what "SubscriberBaseClass" means, it could be an extension method over an interface? it could be a real service abstract class to inherit? a dedicated RelyBroker? something else?)

**Comment by loekd** [comment]
I've added a setup: https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors/SubscriberServices/LongRunningTaskSubscriber.cs
Please have a look. It doesn't (yet) process in parallel, but it does buffer incoming messages.
