### ISSUE TITLE
Order of listeners is important

### ISSUE THREAD

**Issue by FloMueh** [loekd/ServiceFabric.PubSubActors#35]
hi loekd,

first of all thank you for the great library. I am using you lib with the service communication.

Everything is working fine. Unless I have a service (WFE, Subscriber) that already has a listener. My service for the WFE creates a KestrelListener. After that I added via `list.AddRange (this.CreateServiceRemotingInstanceListeners ());` the listers for your lib.

After starting the application everything looks fine but the WFE Subscriber does not get any messages. With the error message from PubSubService "Cannot send Message to 0.0.0.0:8080". It seems that the PubSubActors lib always trys to get the first listener (Kestrel) and sends the message to him.  Endpoints should be correct.

After changing the order of the list in the function `protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()` (First: `this.CreateServiceRemotingInstanceListeners()`, Then: KestrelListner) the problem is solved. 

Maybe someone has a similar problem and saves time through this contribution.

Regards,
Florian

**Comment by Expecho** [comment]
Normally you do not have to change the order. You can use named listeners. Unfortunately this package does not yet support that. I am working on a PR for that as I encountered the same issue. It involves having to name the listeners and pass them upon registration.
