### ISSUE TITLE
Failed to add reference to Microsoft.ServiceFabric.Internal

### ISSUE THREAD

**Issue by MarekLani** [loekd/ServiceFabric.PubSubActors#36]
When trying to add ServiceFabric.PubSubActors.PackagedBrokerService nuget package to Service Fabric application I am getting error below. Apparently package is expecting lower version of SF libs. However PubSubActors in version 7.3.2 expects higher version. Plase how is it possible to solve this?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference to 'Microsoft.ServiceFabric.Internal'.
Unable to find a type of reference that is appropriate for this file: "C:\Users\mlani\Develop\ServiceFabric\PubSub\PubSubSample\packages\Microsoft.ServiceFabric.5.7.198\lib\net45\Microsoft.ServiceFabric.Internal.dll".			0

**Comment by loekd** [comment]
Please use a dedicated Stateful service, like in the [demo code](https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors.Demo/PubSubService/PubSubService.cs), to have more flexibility in version support.
