### ISSUE TITLE
Report Bus Metrics

### ISSUE THREAD

**Issue by Expecho** [loekd/ServiceFabric.PubSubActors#39]
Currently it seems to be impossible to get insights into the load of the bus. For example, getting insights in the size of the queue, the number of subscribers etc.

The BrokerService does report some items to the EventSource using ServiceEventSourceMessageCallback but that is all strings.

How about defining some extra events or actions like ServiceEventSourceMessageCallback 
The information in the EventArgs or action can be used to write it to the EventSource, create a custom HealthReport or Metric or something else.

What would be the preferred way and do you think it will add value as well? If so I could develop one of the scenario's and create a PR.

**Comment by loekd** [comment]
I like the idea! 
We could add SF health metrics like 

- QueueStatus - Reporting subscriber queue depths (growing == unhealthy).
- Processing Time - Reporting the amount of time spent in dispatching messages (longer than x == unhealthy)

And maybe some structured callbacks providing info like:

- Messages /s received
- Messages /s dispatched
- Total Messages received
- Total Messages dispatched
- Message received
- Message dispatched

**Comment by Expecho** [comment]
I think I will start with the structured callbacks. It does have the least impact.
Health reports / metrics can be added directly but another option would be to leave that decision to the consumer of the library, provided the library does output the details needed to do this. 

I was kind of busy but I will get started soon and then we can take a look at the implementation.

**Comment by danadesrosiers** [comment]
Has this work been abandoned?  I'm looking into implementing such features.  I can pick it up.

**Comment by loekd** [comment]
As always, anyone is free to contribute! So please do.

**Comment by danadesrosiers** [comment]
v9.0.0 includes an endpoint on IBrokerService to get Broker stats and adds Broker Events that can be subscribed to for additional customization.
