### ISSUE TITLE
Auto resubscription

### ISSUE THREAD

**Issue by koderi-dp** [loekd/ServiceFabric.PubSubActors#42]
When  checking actor events, is it possible to implement same logic for subscribers?

From https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-events

In the event of failovers, the actor may fail over to a different process or node. The actor proxy manages the active subscriptions and automatically re-subscribes them

**Comment by loekd** [comment]
Messages are sent to an Actor based on an ActorRefence. The location of the Actor is abstracted away by this mechanism.
So it should just keep working after fail over.

Sent from Nine<http://www.9folders.com/>.
________________________________
Van: danijel-peric <notifications@github.com>
verzonden: vrijdag 15 juni 2018 17:03
Aan: loekd/ServiceFabric.PubSubActors
Cc: Subscribed
Onderwerp: [loekd/ServiceFabric.PubSubActors] Auto resubscription (#42)


When checking actor events, is it possible to implement same logic for subscribers?

From https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-events

In the event of failovers, the actor may fail over to a different process or node. The actor proxy manages the active subscriptions and automatically re-subscribes them

**Comment by koderi-dp** [comment]
ok, thanks
