### ISSUE TITLE
Partition Id

### ISSUE THREAD

**Issue by koderi-dp** [loekd/ServiceFabric.PubSubActors#44]
Maybe it's not best practice and should be avoided, but i noticed something in tests (1 dev node), if you publish broker service and then publish subsriber service, subscriber will be registered with partition id at that moment, it will start to receive messages, broker service will publish messages to all subscribers at that moment for that message type, now if you republish same service not upgrade, service will get new partition id, this will be regiatered in broker as 2 subscribers, same subsriber same endpoint but with different partition id, and when that hapens broker will publish same message to both subsribers, but in this case same subsriber will receive 2 messages

Subsriber service is singleton, maybe checking when creating service proxy for subsriber on that partition id if it is alive?

**Comment by loekd** [comment]
Nice catch again. I recommend to unsubscribe your service when it shuts down. 
I've changed the `ServiceReferenceWrapper` code to not use the `PartitionGuid` anymore. Instead, it uses the app name, service name and if present partitionkey / partitionname.
Let me know if this works out for you.

**Comment by koderi-dp** [comment]
I have implemented unsubscribe onclose etc what ever is available to overwride, but it looks like sf when you publish the app is deleting old one without normal shutdown, unsubscribe is never received by broker, will test and let you know

**Comment by koderi-dp** [comment]
Just quick question, is there a reason why this library isnt switched to net standard? I have done this without any issues, have to do it because im using net core services

**Comment by loekd** [comment]
Haven't gotten around to it yet.
Happy to take pr's!

Sent from Nine<http://www.9folders.com/>
________________________________
Van: danijel-peric <notifications@github.com>
verzonden: dinsdag 26 juni 2018 21:08
Aan: loekd/ServiceFabric.PubSubActors
Cc: loekd; Comment
Onderwerp: Re: [loekd/ServiceFabric.PubSubActors] Partition Id (#44)


Just quick question, is there a reason why this library isnt switched to net standard? I have done this without any issues, have to do it because im using net core services

**Comment by koderi-dp** [comment]
ok, published it to https://github.com/danijel-peric/ServiceFabric.Notification

you can use this example if you like, for me realtime clock with signalR is ok to see how the pub/sub performs in some light way

**Comment by loekd** [comment]
Nice example project! 

v7.4.0 has netstandard2.0 support.
Please let me know if it works for you.

**Comment by koderi-dp** [comment]
Working
