### ISSUE TITLE
Interest Becoming a Maintainer

### ISSUE THREAD

**Issue by JustinCouto** [loekd/ServiceFabric.PubSubActors#49]
Hi There, 

My team has been using this project and would love to start contributing to it on a regular basis.  We use SF we like what you have here.  We recently submitted a pull request and have not got a response on it yet.  If you have become too busy to focus on this project or if you are no longer interested in doing so, we'd be happy to take over maintaining it for you.  If you are interested, please let me know.  We will commit to being responsive and working with the community to continue the great work you started.

**Comment by loekd** [comment]
Hi @JustinCouto , first of all; apologies for the late response, I'm usually much earlier, but it's been an extremely busy week on my day job. 

Thank you and @danadesrosiers for the contributions. Always happy to receive them!
When contributions keep coming like you say, we can definitely work together on this.

**Comment by JustinCouto** [comment]
Great!  What would be the best way for us to send you the ideas we have on how to move things forward?  Should we just submit PRs with explanations on why we think the changes are good?  Do you want us to send you what ideas we have?  We need to move fast on this and we want to do what we can to work best with you.  If you are interested in what we have done as an organization in open source, you can check out http://www.AngularPlayground.it.  If you are interested, we'd like to put a similar effort into this project complete with a site and docs.  Let me know what you think.

**Comment by loekd** [comment]
Sounds very good! I propose we go with PR's for a short while and when it works out, I'll add you as collaborators.
Definitely curious to hear your ideas.

**Comment by JustinCouto** [comment]
That sounds good!

We like the changes you made and think thery're great.  We will continue to work on it and submit PRs ffor your approval.  One thing we have been wondering is if we are missing something on the Actor Broker part of the project.  It seems like it is inferior to the service broker and we were wondering if we were missing why it is useful.  If it is in fact inferior, we were wondering if you'd be open to dropping it from the project to further simplify it making it more focused, easier to learn and easier to use.  If we are missing something, we'd love to understand it more.  Any feedback on this you could provide would be awesome.

THanks again!

**Comment by loekd** [comment]
About the `BrokerActor`, I completely agree. In fact, let's mark it as `Obsolete` [straight away](https://github.com/loekd/ServiceFabric.PubSubActors/pull/54).

**Comment by loekd** [comment]
While we're at it, we can deprecate the entire `Interfaces` library as well.

**Comment by JustinCouto** [comment]
That is great.  I love the idea of keeping it as focused and simple as possible.  Let's make it amazing at doing what it does one way.  Thank you.  We'll continue to work at it and submit PRs.

**Comment by loekd** [comment]
Dana is now a collaborator, so I think this can be closed. Please reopen if needed.

**Comment by JustinCouto** [comment]
Hey There, 

I have been meaning to write you again.  I was wondering if you'd be up to working this project at a higher level.  We plan to continue a sustained effort on it over time.  We'd like to create a website, put up documentation, and promote the project and hopefully make it more known and used.  Here are a couple of our other projects:

http://AngularPlayground.it
http://service-fabric-distributed-cache.socreate.it

We'd love to bring this project into the fold.  Would you be open to discussing that?

**Comment by loekd** [comment]
Yes I am, it sounds great. Let's do it!

**Comment by JustinCouto** [comment]
Would you be willing to make the organization SoCreate a project owner on the project? We'd add Dana, Jami Lurock or Chief of Software, Brian Treese our Chief of UX, and I as admin's on the project.  We'd still of course be collaborating with you and doing PR's through you if you prefer that.  What are your thoughts on this?
