### ISSUE TITLE
Subscribing to events with particular property value from Actors

### ISSUE THREAD

**Issue by pavelbaykov89** [loekd/ServiceFabric.PubSubActors#5]
Is it possible to subscribe from Actors to the events with particular property value? 
The example:
PersonActor should susbcribe to events that have PersonId of this PersonActor and I don't want other PersonActor instances with different PersonId values to receive this message. Or maybe it's a bad practice and PersonActor should have method instead of receiving message?

**Comment by loekd** [comment]
Hi, this is not possible in the current code. But I do take pull requests. Do you mean something like a Subscription filter in Azure Service Bus [Subscriptions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions)?

Let's see if there's a library that provides this functionality for .net objects.

**Comment by johnkattenhorn** [comment]
@loekd - yep that's the kind of thing we were thinking too. @pavelbaykov89 and I are evaluating the library as a starting position for a project and we would be happy to contribute if we go with it.

**Comment by loekd** [comment]
That would be great!

**Comment by schernets** [comment]
I think this request have to be carefully weighed to make sure it is in the scope of this solution. The solution space is messaging infrastructure. The decimation of events by pub-sub should be agnostic of any domain knowledge unless it is based on a primitive predicate. That _will_ make it domain agnostic. 

Filtering assumes knowledge. Knowledge should be encapsulated in the Domain Model. Messaging infrastructure by definition is not Domain.

These are just thoughts...

**Comment by loekd** [comment]
agreed, the subscriber would need to specify the properties to filter on in a generalized manner.
