### ISSUE TITLE
Broker service locator

### ISSUE THREAD

**Issue by koderi-dp** [loekd/ServiceFabric.PubSubActors#51]
Hi,

I had issue with locating broker service in publisher, subscriber if the publisher or subscriber is not in same application type, so did small change but forgot to commit it, let me know if you want this in pull request

https://github.com/danijel-peric/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors/Helpers/BrokerServiceLocator.cs

**Comment by loekd** [comment]
Hi @danijel-peric , PR's are welcome. So yes, please do so.

**Comment by koderi-dp** [comment]
Closing, implemented in 7.4.2
