### ISSUE TITLE
Routing Key

### ISSUE THREAD

**Issue by koderi-dp** [loekd/ServiceFabric.PubSubActors#55]
Do you think it is possible implementing routing base messaging, example multiple subsribers subsribe to same message type, but have reference to property in message "RoutingKey" so when publisher pushes the message, broker will use routing key prop to find subsriber which is registered for that key and publish the message to only that subsriber.

Something like this

 http://masstransit-project.com/MassTransit/advanced/topology/rabbitmq/routingkey.html

Example case, if i have services which are publising smsmessage type, and have multiple services which are subscribing to smsmessage, and each subscriber has its own implementation of sms provider, smsmessage class contains routing key which provider it should use, routing key is provided by some multitenant application, which has setting for each tenant what sms provider to use for sms alerts, broker could route that message to right subscriber

Hope this makes sense

**Comment by loekd** [comment]
Hi @danijel-peric , please check out [this branch](https://github.com/loekd/ServiceFabric.PubSubActors/tree/RoutingKey). Does that match with your expectations?

**Comment by koderi-dp** [comment]
Yes, thanks, i will try that branch asap

**Comment by loekd** [comment]
Pls check out the tests in `GivenServiceReference`

**Comment by loekd** [comment]
Have a look at v7.6.0 and let me know if it works.
The upcoming version after v8 will add improved support, this is the basic implementation.

**Comment by danadesrosiers** [comment]
Routing Key feature is in the current version.  Please open a new ticket if you have any other suggestions 👍 .
