### ISSUE TITLE
Remove Support for Remoting V1

### ISSUE THREAD

**Issue by danadesrosiers** [loekd/ServiceFabric.PubSubActors#57]
We have had some difficulties with supporting multiple remoting versions.  What do you think about removing support for V1 remoting and exclusively supporting V2?  I think we should at least remove the `useRemotingV2` config since that configuration can be accomplished with assembly references now.  But maybe it's best to only support V2 to help enforce consistency across all services.  It would have to be a major version bump, of course.

**Comment by loekd** [comment]
I believe this is part of the planned v8.

**Comment by danadesrosiers** [comment]
Yes, this is part of v8.
