### ISSUE TITLE
Please consider package the broker as nuget

### ISSUE THREAD

**Issue by tianvan** [loekd/ServiceFabric.PubSubActors#6]
like this：[SFNuget](http://haishibai.blogspot.com/2016/08/sharing-your-service-fabric-services-as.html)

**Comment by loekd** [comment]
Hi, do you mean this package? https://www.nuget.org/packages/ServiceFabric.PubSubActors.PackagedBrokerService/

**Comment by tianvan** [comment]
@loekd That‘s awesome.Thank you.

**Comment by loekd** [comment]
You're welcome!
