### ISSUE TITLE
PubSub Project

### ISSUE THREAD

**Issue by JustinCouto** [loekd/ServiceFabric.PubSubActors#63]
HI @loekd 

I had a couple of questions for you.  One I posted on the closed ticket but thought you may not have seen it.  The other below is new:

1. Would you be willing to make our organization SoCreate a project owner on the project? We'd like to add Dana Desrosiers, Jami Lurock or Chief of Software, Brian Treese our Chief of UX, and I as admin's on the project. We'd still, of course, be collaborating with you, with you running the project and approving PR's if you prefer it that way. 

2. We'd like to rename the project repository to service-fabric-pubsub and call the project Service Fabric PubSub.

If you are okay with all of this, we will get a site set up like those other sites I showed you and we will start promoting the project to see if we can increase its visibility and awareness of it.  We will also continue to work on the project.  For example, we are interested in adding a UI that will give you the ability to look at queue stats and allow you to unsubscribe through the UI.

We are excited about this project and have enjoyed working with you on it.  We are now interested in taking it to the next level with you if you are on board with these ideas.  If you are not, we totally understand.

I look forward to hearing from you.

Thank you, 
Justin

**Comment by loekd** [comment]
Hi, I didn't miss it, I needed some time to consider. We can probably do this, I like it a lot! I do have some concerns I want to discuss first:
- The project must stay open source and open to receive contributions from anyone.
- I cannot be the bottleneck in PR approval/ review at the current rate, as I have a busy life. I would like very much to be be involved in design discussions before new features are implemented. (architecture level, not as the emperor, but as a participant)
- I'd like to get some kind of visible accreditation for present work.

**Comment by JustinCouto** [comment]
Absolutely, I agree.  We would always keep it open source and receive contributions from anyone as long as we all agree they make sense for the project.  We'd love for you to stay involved and contribute as your much as you can.  We would absolutely credit you for starting the project and your work on it.  For example, we'd put your avatar on the site and any info you'd like us to share and at the bottom of the site, it would say made with love by you and SoCreate. We can post tickets about design changes we'd like to make and discuss them much like we are discussing this if that works for you.  We don't want to take anything away from you or anyone else.  We just need to be more of a part of it to contribute a continued effort of resources.

Let uss know what you decide and we will be good with it either way.

What are your thoughts on the name changes?

**Comment by loekd** [comment]
Great! The name changes totally make sense, I never wanted to change it because the github url would change, making the project harder to find. But as we're doing that anyway, we might as well make it a proper one.
Let's go for it!

**Comment by JustinCouto** [comment]
Awesome!  Are you ready to move forward with the other things as well?

**Comment by loekd** [comment]
Yes

**Comment by loekd** [comment]
Please allow me to transfer ownership and remove the current fork, so I can transfer to SoCreate.

**Comment by JustinCouto** [comment]
Great!  We'll get started on. The site and we'll add you to the documentation/site repository once we get it setup.  We all look forward to working with you more on this project and watching it grow.  Thanks for starting it and for working with us on it.

**Comment by JustinCouto** [comment]
We removed the fork.  Also, how would you like us to list you on the site?  Do you want us to just use Loekd?  Do you have a photo or avatar you'd like us to use?  Do you have a twitter profile you'd like us to link to or do you just want us to link to your GitHub profile?

Please let us know.  We have already begun working on the site and would like to go live with it next week.  Thank you!
Justin

**Comment by loekd** [comment]
I've requested transfer to @danadesrosiers  so the repo can be transferred to SoCreate without me having repo creation rights.
My [profile](https://github.com/loekd) now has a photo, can you please link to & use that?

**Comment by JustinCouto** [comment]
Great!  Thank you.  We already started working on the site and should have it up next week sometime. The url for it will be http://service-fabric-pub-sub.SoCreate.it

**Comment by danadesrosiers** [comment]
The project is now live at its new home.
