### ISSUE TITLE
Subscribe attribute when subscriber starts before broker

### ISSUE THREAD

**Issue by theted007** [loekd/ServiceFabric.PubSubActors#66]
Firstly well done on a great project!

We are using the project using the Subscribe Attribute but it appears that if the message broker is not running on startup then the subscription never happens. I can see from the base class that subscription is only attempted when the service opens.

My question is what would you advise regarding calling Subscribe explicitly. I have considered a 'heartbeat' message being published at a short interval, and if the subscriber does not receive a heartbeat within a reasonable time span it can call base.Subscribe() at that point, though this feels wasteful and possibly unnecessary.

Looking at the base class, any exception thrown is logged and ignored, so I could fork the project and maintain some state indicating that an exception was thrown, indicating that base.Subscribe() should be called again after some brief pause.

Looking forward to hearing your thoughts.

**Comment by danadesrosiers** [comment]
Thank you for the feedback!  Yeah, it looks like we could do a better job of managing that situation.  I think we can add a retry strategy to the Subscribe logic.  And we should throw that exception so the implementer can override the `Subscribe()` method to catch exceptions and handle the issue in their own way.

There is also a new feature in v9.0 that may be helpful to you.  The BrokerClient has a new method `GetBrokerStatsAsync()` that will provide a list of all subscribed services and some statistics on them.  You could use that to confirm programatically that you are subscribed.  The name of the package changed, so find v9.0+ at the new NuGet package: https://www.nuget.org/packages/SoCreate.ServiceFabric.PubSub/

**Comment by danadesrosiers** [comment]
Check out #67 and let me know if that gives you what you need.  I think you should be able to do whatever custom error handling and retry strategies you need by overriding `OnOpenAsync()` and/or `Subscribe()`.

**Comment by danadesrosiers** [comment]
Subscribe retry is implemented in v9.1.0.
