### ISSUE TITLE
Can a Broker also subscribe to messages?

### ISSUE THREAD

**Issue by bhalbright** [loekd/ServiceFabric.PubSubActors#70]
I started playing with this project last week. Amazing, fits a great need. I have a use case where I want to publish a message and have all service fabric services receive it (including the broker itself - the use case is to tell services to adjust their logging). I have no trouble getting the subscriptions working in all the services except for the broker. I'm wondering it if is possible? A few feeble attempts to do this didn't quite work (new BrokerClient() seems to hang for several minutes). I tried to wait until the BrokerService had been created (i.e. not subscribing in OnOpenAsync) but it was the same issue. Sorry if this isn't enough information. I'm mainly interested in the question of is this technically possible, thanks!

**Comment by danadesrosiers** [comment]
Interesting question.  It is a bit weird using remoting to make a call to yourself, but I don't see why it couldn't work.  To be sure, I gave it a try.  You're right, you can't subscribe in OnOpenAsync because the StateManager is not available yet.  You have to do it in RunAsync.  I got a working example by modifying the Broker in the Demo App like this:

```
internal sealed class Broker : BrokerService, ISubscriberService
{
    private readonly BrokerClient _brokerClient;

    public Broker(StatefulServiceContext context) : base(context)
    {
        _brokerClient = new BrokerClient();
        ServiceEventSourceMessageCallback = message => ServiceEventSource.Current.ServiceMessage(context, message);
        Period = TimeSpan.FromMilliseconds(200);
    }

    protected override async Task RunAsync(CancellationToken cancellationToken)
    {
        await _brokerClient.SubscribeAsync<SampleEvent>(this, HandleSampleEvent);
        ServiceEventSource.Current.ServiceMessage(Context, "Broker Subscribed to SampleEvent");
        await base.RunAsync(cancellationToken);
    }

    public Task ReceiveMessageAsync(MessageWrapper message)
    {
        return _brokerClient.ProcessMessageAsync(message);
    }

    private Task HandleSampleEvent(SampleEvent sampleEvent)
    {
        ServiceEventSource.Current.ServiceMessage(Context, $"Processing SampleEvent: {sampleEvent.Message} on Broker");
        return Task.CompletedTask;
    }
}
```

**Comment by bhalbright** [comment]
Thanks @danadesrosiers for your quick response. That worked for me as well. I should have thought to try in RunAsync. Thanks again!
