### ISSUE TITLE
My broker service name must be PubSubBroker?

### ISSUE THREAD

**Issue by buzzers** [loekd/ServiceFabric.PubSubActors#76]
I noticed that in the https://service-fabric-pub-sub.socreate.it/docs/getting-started/setup-pubsub-broker on this page, "Add a new Stateful Service Project. We'll call it 'PubSubBroker.", can I understand that the name of the broker service must be **PubSubBroker**?

**Comment by danadesrosiers** [comment]
The broker service must extend `BrokerService`, but can have any name you want to give it.

**Comment by buzzers** [comment]
thanks, got it!
