### ISSUE TITLE
Actor Subscriber Communication Endpoint Version is V2_1

### ISSUE THREAD

**Issue by buzzers** [loekd/ServiceFabric.PubSubActors#77]
In the latest stable version of ServiceFabric (3.4.641.0), the default endpoint version for the reliable actors created is V2_1.
The service-fabric-pub-sub document states that the actor subscriber's version must be V2. 
Does this cause problems?

According to Azure's documentation, it seems that V2_1 and V2 are compatible?

**Comment by danadesrosiers** [comment]
I don't think it will work out of the box using V2_1, but you can configure your Actors to use V2 remoting instead using an assembly attribute.  This is shown in the documentation [here](https://service-fabric-pub-sub.socreate.it/docs/how-to/subscribe-to-messages#using-actors).  See the assembly attribute on `ISubscribingActor`.

**Comment by buzzers** [comment]
But the new reliable actor service with the latest version of The Service Fabric template from Visual Studio 2019 uses EndpointV2_1 by default, so I'm worried about whether modifying this default configuration will cause problems.
My project endpoint XML is define like
```XML
<Resources>
  <Endpoints>
    <Endpoint Name="CredentialsActorServiceEndpointV2_1" />
    <Endpoint Name="CredentialsActorServiceReplicatorEndpoint" />
  </Endpoints>
</Resources>
```

**Comment by danadesrosiers** [comment]
Yeah, you do need to change that to `CredentialsActorServiceEndpointV2`.  I don't think there's anything to worry about there, it's just configuring remoting.

**Comment by buzzers** [comment]
OK, I try it.
