### ISSUE TITLE
Not able to Unregister a subscriber that implements the ISubscriberService

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#8]
I have a Stateless subcriber that implements my IMySubscriber which inherits from ISubscriberService.  IMySubscriber has some of my custom methods So I am trying to locate this subscriber using IServiceProxyFactory using the IMySubscriber. I have an API gateway but `proxyFactory.CreateServiceProxy<IMySubscriber >(serviceUri.ToUri())`. I think it is able to locate the service instance but when I invoke a method in my IMySubsciber method it will get a ""Client is trying to connect to invalid address net.tcp..."

**Comment by alltej** [comment]
bottom line is i need to unregister a particular subscriber

**Comment by loekd** [comment]
I think the reason for this error is that you're trying to use SFRemoting to communicate with a service that is configured to use WCF communication (inside `SubscriberCommunicationListener`). 

- If you want to add remoting support:

return an additional ICommunicationListener of type `FabricTransportServiceRemotingListener` from `CreateServiceInstanceListeners`.

Example:

```
yield return new ServiceInstanceListener(p => new SubscriberCommunicationListener(this, p), "StatelessSubscriberCommunicationListener");
yield return new ServiceInstanceListener(context => new FabricTransportServiceRemotingListener(context, this), "StatelessFabricTransportServiceRemotingListener");
```

You can now communicate to it using both WCF and SFRemoting.

Example:

```
var subStateless = ServiceProxy.Create<ISubscribingStatelessService>(new 	
	Uri("fabric:/MyServiceFabricApp/SubscribingStatelessService"),
	listenerName: "StatelessFabricTransportServiceRemotingListener");
subStateless.UnregisterAsync().ConfigureAwait(false).GetAwaiter().GetResult();
```
(notice the listenerName)
 

- If you want to use WCF to communicate, read [this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-wcf).

- If you want to unsubscribe a service, from within the service, just use `SubscriberServiceHelper`.


- For a complete example, check out the [Demo ](https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors.Demo/SubscribingStatelessService/SubscribingStatelessService.cs#L72) [project](https://github.com/loekd/ServiceFabric.PubSubActors/blob/master/ServiceFabric.PubSubActors.Demo/TestClient/Program.cs#L43).

**Comment by alltej** [comment]
Thanks @loekd ! I am using the ServiceFabric.PubSubActors nuget package for my pub/sub. So far it is working but at some point I need to add a way unregister a stateless subscriber. That's when I also realized the underlying communication listener is using WcfCommunicatonListener. What are the advantage/disadvantage of using one over the default FabricTransportServiceRemotingListener?

**Comment by alltej** [comment]
When I use multiple listeners as you have suggested, I am getting this errors below. Although I initialized the client proxy using the IServiceProxyFactory. 

Client is trying to connect to invalid address net.tcp://localhost:49671/3d826454-fe5e-4e9e-a0a4-4caf7215047a/63c2b70b-3cb0-4592-bde3-1fe1eee8fece-131291297409015244.

**Comment by alltej** [comment]
Actually, it is working now. Again, I forgot this "listenerName" parameter. Thanks!
