### ISSUE TITLE
Update documentation (broker setup)

### ISSUE THREAD

**Issue by Plankton555** [loekd/ServiceFabric.PubSubActors#83]
The example on the doc page https://service-fabric-pub-sub.socreate.it/docs/getting-started/setup-pubsub-broker does not compile.

I think the problem is that `this` is passed as an argument instead of a StatefulServiceContext.

```
ServiceEventSourceMessageCallback = message => ServiceEventSource.Current.ServiceMessage(this, message);
```
should be
```
ServiceEventSourceMessageCallback = message => ServiceEventSource.Current.ServiceMessage(context, message);
```

**Comment by danadesrosiers** [comment]
Ah, you are correct.  Thanks for reporting this, I'll get it fixed right away.
