### ISSUE TITLE
Is there helper method to get the events the subscriber service is registered to?

### ISSUE THREAD

**Issue by alltej** [loekd/ServiceFabric.PubSubActors#9]
So far my pub/sub using this nuget package is working. Now I need to provide info about these available subscribers and their events. Is there helper method to get the events the subscriber service is registered to?

**Comment by loekd** [comment]
Good to read that the package is working.

There's no built in query support at this time.  

- Option 1.
Use the framework: Publish a message that describes what messages a subscriber has subscribed to. Create a subscriber for those messages, keep a registry, and enable queries on that subscriber. 
If you do this, please consider contributing this query service to the repo using a PR.


- Option 2.
Add code:
If you're using a custom Service project that is your BrokerService, you could add operations there to answer queries. For instance, getting all subscribers for a given `messageType `(fully qualified typename) from a partition would be:

```
var myDictionary = await TimeoutRetryHelper.Execute((token, state) =>   StateManager.GetOrAddAsync<IReliableDictionary<string, BrokerServiceState>>(messageType));

var subscribers = await TimeoutRetryHelper.ExecuteInTransaction(StateManager, async (tx, token, state)           
               =>
      {
         var result = await myDictionary.TryGetValueAsync(tx, Subscribers);
         if (result.HasValue)
          {
             return result.Value.Subscribers.ToArray();
          }
          return null;
     });
```

If you then use SF Remoting for interaction with these additional operations, they won't interfere with the pub/sub behavior. Query all partitions to get all answers.

**Comment by alltej** [comment]
will work on your suggestion solution and will send a PR once complete. thanks!

**Comment by loekd** [comment]
Thank you!

**Comment by alltej** [comment]
@loekd for Option 1 you mentioned previously, in the case of service broker (i think will also apply to service actor), can I just expose a method in the BrokerService base class that will read the dictionary of the registered subscribers?
