### ISSUE TITLE
Suggestion/Idea: Wild Card Support For RoutingKey

### ISSUE THREAD

**Issue by Calidus** [loekd/ServiceFabric.PubSubActors#93]
Wildcard support for Routing Keys would be really nice.  Would it be as simple as updating ```ShouldDelieverMessage(MessageWrapper message)```?

Even just a basic StartsWith instead of equals would go a long way. I think you could pick a character(or two) to mean StartsWith and use that instead of equals. Another option would be add a feature flag to the subscribe attribute.

**Comment by danadesrosiers** [comment]
Thanks for the suggestion!  This feature is not on our roadmap right now, but if you want to give it a shot and submit a PR, we would be happy to review it.

**Comment by Calidus** [comment]
Do you have a preference between adding a bool to the Subscribe Attribute vs picking a symbol besides '='?

**Comment by danadesrosiers** [comment]
I think a simple `*` wildcard would work:

// Equals "foo"
`[Subscribe(routingKey: "Message=foo")]`

// Starts With "foo"
`[Subscribe(routingKey: "Message=foo*")]`

// Ends With "foo"
`[Subscribe(routingKey: "Message=*foo")]`

// Contains "foo"
`[Subscribe(routingKey: "Message=*foo*")]`

**Comment by danadesrosiers** [comment]
Feature is now available in v12.2.0!
