### ISSUE TITLE
Competiting Comsumers

### ISSUE THREAD

**Issue by Calidus** [loekd/ServiceFabric.PubSubActors#96]
There is no out of box support for competing consumers right? Options seem to be:

- Make work manager service that subscribes to a queue and divides up messages between workers
- Abuse routing key feature, and partition messages as they are generated
- Make a PR? Add a new QueueType enum, and edit the broker

**Comment by danadesrosiers** [comment]
You are correct, there is nothing built in to support this.  The first two options you mentioned are definitely available to you now.  Partitioning via routing key seems like a good option.  I'm not sure I would even consider it abuse.

I can see how having something built in would provide value.  Maybe there would be a "subscriberId" on the `Subscribe` attribute and all subscribers with the same Id would share a queue.  We would have to come up with a strategy (or strategies) to govern how messages are distributed across the set of competing subscribers.  It would likely require significant work and breaking changes.  We're not prepared to take it on right now.  If you really want to pursue this feature, we would ask that you put together a proposal for how it would be implemented.  When we have a plan that we are all happy with, we would then give you the green light to begin a PR.
