### ISSUE TITLE
The provided URI scheme 'https' is invalid; expected 'http'. Parameter name: via

### ISSUE THREAD

**Issue by Gowri1205** [loekd/ServiceFabric.PubSubActors#98]
here my web.config

<bindings>
<basicHttpBinding>
<binding name="BasicHttpBinding_IWorkerProcessService">
<security mode="Transport">
<transport clientCredentialType="Basic"/>
</security>
</binding>
<binding name="BasicHttpBinding_IWorkerProcessService1"/>
</basicHttpBinding>
</bindings>
<client>
<endpoint address="http://xxxxxxxx/WorkerProcessService.svc" binding="basicHttpBinding"
bindingConfiguration="BasicHttpBinding_IWorkerProcessService" contract="ServerReference.IWorkerProcessService"
name="BasicHttpBinding_IWorkerProcessService"/>
</client>

I get this error The provided URI scheme 'http' is invalid; expected 'https'

Please give solution for this

**Comment by danadesrosiers** [comment]
Hi @Gowri1205,

I will not be able to provide any guidance without some context.  What are you attempting to do?  Steps to reproduce?  I will say that Service Fabric PubSub uses Service Fabric remoting, not http, so whatever is going on does not appear to be related to this library.

**Comment by Gowri1205** [comment]
here my web.config

bindings
basicHttpBinding
binding name="BasicHttpBinding_IWorkerProcessService"
security mode="Transport"
binding name="BasicHttpBinding_IWorkerProcessService1"
basicHttpBinding
bindings
client
endpoint  #address="http://xxxxxxxx/WorkerProcessService.svc" binding="basicHttpBinding"
bindingConfiguration="BasicHttpBinding_IWorkerProcessService" contract="ServerReference.IWorkerProcessService"
name="BasicHttpBinding_IWorkerProcessService"


I get this error The provided URI scheme 'http' is invalid; expected 'https'

Please give solution for this url

**Comment by Gowri1205** [comment]
> Hi @Gowri1205,
> 
> I will not be able to provide any guidance without some context. What are you attempting to do? Steps to reproduce? I will say that Service Fabric PubSub uses Service Fabric remoting, not http, so whatever is going on does not appear to be related to this library.

Above code is okey?

**Comment by danadesrosiers** [comment]
I'm not sure what you're doing with web.config.  Honestly, I'm not familiar with that config.

I need to know what action are you taking that produces the error and what your setup looks like.  Are you trying to run the example app?  What framework version are you running?  .NET Framework or .NET Core?  What version of Service Fabric?  Do you have the Broker running?  Do you have a Subscriber service running?  How are you publishing messages?  You could post some code snippets showing how you have set up you Broker and Subscriber, etc.
