### ISSUE TITLE
Add support for using custom serialization for remoting communication messages

### ISSUE THREAD

**Issue by pretyk** [loekd/ServiceFabric.PubSubActors#99]
Currently service fabric pub sub supports only the default remoting communcation messages which are xml serialized. Many projects use custom remoting serialization (such as custom json serializers), and cannot integrate with this project

**Comment by danadesrosiers** [comment]
Version 12.3.0 has been released.  For anyone following this feature request:

We ended up creating an interface `IProxyFactories` that is responsible for creating the Service and Actor proxies for remoting communication.  Users can write their own implementation and pass it to the `BrokerService` and `BrokerClient` to override the default implementation.  See the [documentation](https://service-fabric-pub-sub.socreate.it/docs/how-to/broker-configuration) and the [Demo App](https://github.com/SoCreate/service-fabric-pub-sub/tree/master/examples/SoCreate.ServiceFabric.PubSubDemo.Common) for more details.

Thank you @pretyk!
